## Atividade rapida

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
caminho = '07_arquivos/portal_dados_climaticos.csv'

dados_df = pd.read_csv(caminho, sep=';', encoding='utf-8', low_memory=False)

In [9]:
display(dados_df)

,Data,Hora (UTC),Temp. Ins. (C),Temp. Max. (C),Temp. Min. (C),Umi. Ins. (%),Umi. Max. (%),Umi. Min. (%),Pto Orvalho Ins. (C),Pto Orvalho Max. (C),Pto Orvalho Min. (C),Pressao Ins. (hPa),Pressao Max. (hPa),Pressao Min. (hPa),Vel. Vento (m/s),Dir. Vento (m/s),Raj. Vento (m/s),Radiacao (KJ/m²),Chuva (mm)
0,01/05/2024,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01/05/2024,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01/05/2024,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01/05/2024,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01/05/2024,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2971,01/09/2024,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2972,01/09/2024,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2973,01/09/2024,2100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2974,01/09/2024,2200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2975,01/09/2024,2300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
dados_df = dados_df.dropna()
display(dados_df)

,Data,Hora (UTC),Temp. Ins. (C),Temp. Max. (C),Temp. Min. (C),Umi. Ins. (%),Umi. Max. (%),Umi. Min. (%),Pto Orvalho Ins. (C),Pto Orvalho Max. (C),Pto Orvalho Min. (C),Pressao Ins. (hPa),Pressao Max. (hPa),Pressao Min. (hPa),Vel. Vento (m/s),Dir. Vento (m/s),Raj. Vento (m/s),Radiacao (KJ/m²),Chuva (mm)
13,01/05/2024,1300,"29,8","30,2","27,9","63,0","75,0","63,0","21,9","23,8","21,9","1009,1","1009,5","1009,1","2,4","125,0","8,8","1572,90","0,0"
14,01/05/2024,1400,"29,8","30,2","29,4","62,0","67,0","60,0","21,7","22,9","21,3","1008,7","1009,1","1008,7","2,7","137,0","10,4","1597,10","0,0"
15,01/05/2024,1500,"31,0","31,1","29,8","59,0","65,0","59,0","22,1","23,1","21,7","1007,5","1008,7","1007,5","2,6","123,0","6,5","1859,90","0,2"
16,01/05/2024,1600,"30,1","32,2","30,1","61,0","63,0","56,0","21,9","23,6","21,1","1006,9","1007,5","1006,9","1,9","126,0","6,7","2074,40","0,0"
17,01/05/2024,1700,"31,2","31,9","30,1","57,0","63,0","56,0","21,8","23,3","21,3","1006,3","1006,9","1006,2","3,4","107,0","7,6","1840,70","0,0"
18,01/05/2024,1800,"31,0","31,5","30,4","56,0","61,0","55,0","21,3","22,4","21,0","1006,1","1006,4","1006,1","3,1","107,0","7,7","1751,40","0,2"
19,01/05/2024,1900,"30,2","31,1","29,9","61,0","63,0","55,0","21,8","22,4","20,9","1006,1","1006,2","1006,0","2,6","105,0","7,1","1244,30","0,0"
20,01/05/2024,2000,"29,3","30,2","28,9","67,0","68,0","61,0","22,5","22,7","21,6","1006,4","1006,4","1006,1","1,7","104,0","5,6","462,70","0,0"
37,02/05/2024,1300,"29,6","30,4","29,1","67,0","74,0","64,0","22,8","24,2","22,4","1008,2","1008,5","1008,2","2,3","136,0","6,0","1862,80","0,2"
38,02/05/2024,1400,"30,6","31,1","29,5","60,0","68,0","59,0","21,8","23,6","21,7","1007,7","1008,3","1007,7","2,1","141,0","6,8","1750,10","0,0"
39,02/05/2024,1500,"29,8","30,9","29,1","63,0","66,0","56,0","22,0","22,6","20,5","1006,7","1007,7","1006,7","1,6","131,0","6,7","839,00","0,0"
40,02/05/2024,1600,"30,7","31,1","29,8","58,0","65,0","55,0","21,4","22,9","20,5","1005,6","1006,7","1005,6","2,4","130,0","6,2","1716,60","0,0"
41,02/05/2024,1700,"31,7","32,0","30,7","57,0","59,0","51,0","22,3","22,4","20,2","1004,9","1005,6","1004,9","2,4","125,0","6,5","2096,90","0,2"
42,02/05/2024,1800,"31,1","31,8","31,1","56,0","59,0","54,0","21,3","22,4","21,2","1004,5","1004,9","1004,5","2,9","112,0","6,8","1838,20","0,0"
43,02/05/2024,1900,"30,4","31,3","30,4","59,0","59,0","55,0","21,4","21,9","20,9","1004,4","1004,6","1004,4","2,8","111,0","7,4","1373,80","0,0"
44,02/05/2024,2000,"29,3","30,5","29,3","64,0","64,0","57,0","21,8","21,9","20,9","1004,8","1004,8","1004,4","2,2","103,0","7,0","727,30","0,0"
60,03/05/2024,1200,"28,3","28,4","26,7","80,0","100,0","80,0","24,5","27,2","24,5","1007,6","1007,6","1007,1","2,1","150,0","6,0","1080,70","0,0"
61,03/05/2024,1300,"27,5","28,7","26,7","84,0","89,0","78,0","24,6","26,0","23,8","1007,5","1007,7","1007,5","2,9","132,0","7,9","1315,50","0,2"
62,03/05/2024,1400,"29,8","30,3","27,5","74,0","85,0","71,0","24,6","25,7","23,9","1007,0","1007,5","1007,0","2,5","164,0","6,8","2137,50","0,0"
63,03/05/2024,1500,"28,8","29,8","27,9","74,0","84,0","71,0","23,8","25,7","23,3","1006,2","1007,0","1006,2","4,5","107,0","10,8","1495,40","0,0"
64,03/05/2024,1600,"31,1","31,2","28,3","67,0","77,0","64,0","24,2","24,7","23,2","1005,3","1006,2","1005,3","2,4","120,0","10,8","1591,20","0,0"
65,03/05/2024,1700,"30,5","31,4","30,0","63,0","71,0","63,0","22,8","25,0","22,7","1004,7","1005,3","1004,7","4,4","104,0","9,5","1943,30","0,0"
66,03/05/2024,1800,"30,5","31,1","30,4","67,0","68,0","62,0","23,7","24,0","22,8","1004,3","1004,7","1004,3","2,9","102,0","9,5","1821,70","0,0"
67,03/05/2024,1900,"29,8","30,6","29,8","67,0","70,0","65,0","23,0","23,9","22,9","1004,8","1004,8","1004,3","2,6","124,0","8,7","1181,30","0,0"
89,04/05/2024,1700,"29,8","30,3","29,4","70,0","70,0","62,0","23,6","23,7","22,0","1006,9","1007,0","1006,8","2,0","110,0","6,4","931,00","0,0"
108,05/05/2024,1200,"29,3","29,8","28,2","64,0","73,0","64,0","21,9","23,6","21,9","1008,9","1009,2","1008,8","3,2","163,0","7,6","1610,90","0,0"
109,05/05/2024,1300,"30,6","31,5","29,2","62,0","66,0","59,0","22,4","23,6","21,7","1008,7","1008,9","1008,7","3,3","147,0","8,4","1849,70","0,0"
110,05/05/2024,1400,"31,0","31,7","30,2","60,0","63,0","58,0","22,4","23,0","21,8","1008,4","1008,8","1008,4","3,0","154,0","9,1","2173,10","0,0"
111,05/05/2024,1500,"31,2","32,2","31,0","57,0","62,0","56,0","21,7","23,1","21,7","1007,5","1008,4","1007,5","2,5","140,0","6,8","1920,20","0,0"
112,05/05/2024,1600,"32,3","32,4","30,5","58,0","63,0","54,0","23,1","23,6","21,7","1006,8","1007,5","1006,8","3,2","116,0","9,1","1824,60","0,0"
113,05/05/2024,1700,"31,6","32,3","31,6","53,0","59,0","52,0","20,9","23,1","20,7","1005,9","1006,8","1005,9","3,8","103,0","10,1","2281,80","0,0"
114,05/05/2024,1800,"31,3","31,8","31,0","61,0","63,0","53,0","22,9","23,4","21,1","1005,9","1006,0","1005,8","3,0","95,0","7,8","1583,80","0,0"
134,06/05/2024,1400,"29,4","30,7","29,4","62,0","65,0","60,0","21,3","22,9","21,1","1007,8","1008,3","1007,8","3,4","128,0","8,5","1651,30","0,0"
135,06/05/2024,1500,"31,3","31,4","29,3","55,0","63,0","55,0","21,1","21,8","20,8","1006,9","1007,8","1006,8","3,8","133,0","9,6","1815,50","0,0"
379,16/05/2024,1900,"30,1","30,7","29,9","65,0","65,0","61,0","22,8","22,9","22,1","1007,5","1007,5","1007,4","4,4","103,0","9,6","116,70","0,0"

# Pesquisa

In [9]:
caminho = '07_arquivos/estacao_dados.csv'

estacao_df = pd.read_csv(caminho, sep=';', encoding='utf-8', low_memory=False)

In [10]:
display(estacao_df)

,Data,Hora (UTC),Temp. Ins. (C),Temp. Max. (C),Temp. Min. (C),Umi. Ins. (%),Umi. Max. (%),Umi. Min. (%),Pto Orvalho Ins. (C),Pto Orvalho Max. (C),Pto Orvalho Min. (C),Pressao Ins. (hPa),Pressao Max. (hPa),Pressao Min. (hPa),Vel. Vento (m/s),Dir. Vento (m/s),Raj. Vento (m/s),Radiacao (KJ/m²),Chuva (mm)
0,01/05/2024,0,"27,6","27,9","27,5","83,0","83,0","78,0","24,4","24,4","23,8","1007,8","1007,8","1007,0",NaN,"17,0",NaN,NaN,"0,0"
1,01/05/2024,100,"27,2","27,7","27,1","85,0","85,0","82,0","24,5","24,6","24,3","1008,2","1008,3","1007,8",NaN,"5,0",NaN,NaN,"0,0"
2,01/05/2024,200,"26,6","27,5","26,6","89,0","89,0","84,0","24,6","24,6","24,4","1008,7","1008,8","1008,1",NaN,"144,0",NaN,NaN,"0,0"
3,01/05/2024,300,"26,4","26,6","26,3","93,0","93,0","89,0","25,1","25,2","24,7","1008,8","1008,9","1008,7",NaN,"117,0",NaN,NaN,"0,0"
4,01/05/2024,400,"26,5","26,5","26,3","91,0","93,0","91,0","24,9","25,1","24,9","1008,2","1008,8","1008,2",NaN,"67,0",NaN,NaN,"0,0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2971,01/09/2024,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2972,01/09/2024,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2973,01/09/2024,2100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2974,01/09/2024,2200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2975,01/09/2024,2300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN